development:
  adapter: postgresql
  encoding: unicode
  database: atm_dev
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: atm_test
  pool: 5
  username:
  password: